backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
dbe = false;
vsync = true;
detect-rounded-corners = true;

corner-radius = 12;
rounded-corners-exclude = [
    "class_g = 'dmenu'"
];

shadow = true;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
